### ISSUE TITLE
Readme.md Organization

### ISSUE THREAD

**Issue by a-camarillo** [DaedalusDreamJournal/66daysofdata#12]
I think the readme should be more of an overview of the repository, it's currently a long list of links which can be better organized in other files.

**Comment by vedanthv** [comment]
Yes. I know. Can you work to make it better

**Comment by vedanthv** [comment]
@a-camarillo I have assigned the task for you. Can you work on creating a nice readme

**Comment by vedanthv** [comment]
I guess you have created a pull request to the DaedalusDreamJournal:DaedalusDreamJournal-patch-3 branch instead of the  DaedalusDreamJournal:master.Can you make the change to the master. Then we can merge the PL
